

# GET http://localhost:3001/users 


GET http://localhost:3001/users/token



# DELETE http://localhost:3001/users/logout
# Content-Type: application/json

# {
#     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldGVyaHloIiwiaWF0IjoxNjgyMDQzNzM0fQ.30TPmFSZtpWpVjYBJdoIWrRHIcprDXTIoIXcx0rAJ8w"
# }

# POST http://localhost:3001/users/login
# Content-Type: application/json

# {
#    "username": "peterhyh",
#    "password": "Peter123$"
# }




# DELETE http://localhost:3001/users